## 0\. Background

*   You have been given a marketing dataset for a bank and you have been tasked with predicting the outcome of a marketing campaign

*   You have a sample dataset with an <font color="red">y</h1></font> target.  


<font color="red"><h1> PRACTIVE LAB </h1></font>

This is a Kaggle dataset and additional information on the dataset can be found at this link https://www.kaggle.com/datasets/prakharrathi25/banking-dataset-marketing-targets

## 1\. Load the Dataset into a Pandas DataFrame

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Project Directory path
project_dir = 'drive/MyDrive/UW.8740/Lab Tests/Lab2/'

In [ ]:
train = pd.read_csv(project_dir+ 'train.csv')
test = pd.read_csv(project_dir+ 'test.csv')

In [ ]:
train

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [ ]:
df = pd.concat([train, test])

### 1\.1 Display the top 5 rows and bottom 5 rows of the DataFrame

<font color="red"><h1> <Submit Answer Below [1]:</h1></font>

In [ ]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

## 2\.Data Exploration

### 2\.1 Identify the number of missing nulls in columns

<font color="red"><h1>Submit Answer Below [2]:</h1></font>

### 2\.2 Identify the most frequently occurring job, education, and marital status in your dataset

<font color="red"><h1>Submit Answer Below [3] :</h1></font>

### 2\.3 Display the unique values of all columns with less than 20 unique values to confirm that they should be considered categorical.

<font color="red"><h1>Submit Answer Below [4] :</h1></font>

## 3\.Pre-process the data

### 3\.1 Organize your columns into Catogorical features, numeric features and target variable

### 3\.2 Feature Transformation


*   One Hot Encoding for Categorical Features.  You may include binary features in the one hot encoding to simplify your code

* You can drop the month column to simplify your code

* Use LabelEncoder to convert the y column from (yes/no) to (0/1)


<font color="red"><h1>Submit Answer Below [5] :</h1></font>

## 4\. Train Predictive Classification Models

Split your data to (80% Training/20% Testing)

Train the three classifiers with no optimization.

Report the following for all classifiers :

*   Confusion Matrix
*   Accuracy Score
*   AUC Score



<font color="red"><h1>Submit Answer Below [6] :</h1></font>

## 5\. Save the models to a file using the pickle library


- show that you can save a model to a file then read the model from the file that you saved

<font color="red"><h1>Submit Answer Below [7] :</h1></font>